# Global path parameters - see params.py for the rest of the parameters
src_path: "src"
out_path: "out"
out_prepared_folder: "prepared"
out_log_folder: "runs"
out_save_folder: "models"
out_checkpoint_folder: "checkpoints"
out_evaluation_folder: "evaluations"

localize_model_folder: "localize"
ocr_model_folder: "ocr"
stack_model_folder: "stack"

dataset_path: "data/datasets/swiss_templates"
prepared_data_path: "data/prepared"
