name: CML
on: [push]
jobs:
  train-and-report:
    runs-on: [self-hosted, cml-runner-gpu]
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install depedencies
        run: |
          pip install -r requirements/requirements.txt
      - name: Set up DVC credentials
        run: |
          dvc remote modify data access_key_id ${{ secrets.MINIO_KEY_ID }}
          dvc remote modify data secret_access_key ${{ secrets.MINIO_ACCESS_KEY }}
      - name: Run DVC pipeline
        run: dvc pull
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo '![](./out/prepared/localize/plots/images/smaple_0.png "Localize Data Sample")' >> report.md
          cml comment create report.md
