name: CML
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  train-and-report:
    runs-on: [self-hosted, cml-runner-gpu]
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install depedencies
        run: |
          pip install -r requirements/requirements.txt
      - name: Set up DVC credentials
        run: |
          dvc remote modify --local data access_key_id ${{ secrets.MINIO_KEY_ID }}
          dvc remote modify --local data secret_access_key ${{ secrets.MINIO_ACCESS_KEY }}
      - name: Run DVC pipeline
        run: |
          dvc pull
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          # Compare parameters to main branch
          echo "# Params workflow vs. main" >> report.md
          echo >> report.md
          dvc params diff main --show-md >> report.md
          echo >> report.md

          # Compare metrics to main branch
          echo "# Metrics workflow vs. main" >> report.md
          echo >> report.md
          dvc metrics diff main --show-md >> report.md
          echo >> report.md

          cml comment create report.md
